baseURL = 'https://hyoungjoojin.github.io/notes'
languageCode = 'en-us'
theme = 'typo'

[params]
home = "/notes"
colorPalette = 'base16-eighties'
hideHeader = true
showFooter = false

[markup]
[markup.highlight]
style = 'solarized-dark'

[caches]
[caches.images]
dir = ':cacheDir/images'
